baseURL = "/"
languageCode = "en-us"
title = "Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    subtitle = ""
    subsite = "default"
    openGraphSiteName = "Tracking Exposed"
    description = "We develop free software to enable research and expert users in figuring out how algorithms shape their online perception."
    tagline = "We fight for a web that is home for many, not property of the few!"

[permalinks]
    posts = "/news/:slug/"

[menu]

 [[menu.main]]
    name = "Manifesto"
    url = "/manifesto"
    weight = 10


 [[menu.main]]
    page = "Tools"
    name = "Tools"
    identifier = "tools"
    weight = 20
 [[menu.main]]
    page = "Facebook"
    identifier = "facebook"
    parent = "tools"
    name= "Facebook"
    url = "https://facebook.tracking.exposed"
    weight = -180
 [[menu.main]]
    page = "YouTube"
    parent = "tools"
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.tracking.exposed"
    weight = -170
 [[menu.main]]
    page = "PornHub"
    parent = "tools"
    identifier = "pornhub"
    name = "PornHub"
    url = "https://pornhub.tracking.exposed"
    weight = -160
 
 
 [[menu.main]]
    name = "Connections"
    identifier = "connections"
    weight = 30

 [[menu.main]]
    parent = "connections"
    name = "Contacts"
    url = "/connections/"
    weight = 10
 [[menu.main]]
    parent = "connections"
    name = "Team"
    url ="/connections/#Reach us:"
    weight = 20
 [[menu.main]]
    parent = "connections"
    name = "Partners"
    url = "/connections/#Actual members:"
    weight = 30


 [[menu.main]]
    name = "Work"
    url = "/work"
    weight = 40






    
#  [[menu.main]]
#    page = "A national-declined research (Italian election)"
#    identifier = "eu19.tracking.exposed"
#    name = "EU Election 2019"
#    parent = "studies"
#    url = "https://eu19.tracking.exposed"
#    weight = -100
#  [[menu.main]]
#    page = "A national-declined research (Italian election)"
#    identifier = "elezioni.tracking.exposed"
#    parent = "studies"
#    name = "Italien Election"
#    url = "https://elezioni.tracking.exposed"
#    weight = -100
# [[menu.main]]
#    page = "PornHub"
#    identifier = "pornhub"
#    parent = "analyzed"
#    name = "PornHub"
#    url = "https://pornhub.tracking.exposed"
#    weight = -160


 [[menu.footer]]
    page = "manifesto"
    identifier = "manifesto"
    name= "Manifesto"
    url = "/manifesto"
    weight =10
 [[menu.footer]]
    page = "tools"
    identifier = "tools"
    name = "Tools"
    url = "/connect"
    weight = 20
 [[menu.footer]]
    page = "connections"
    identifier = "connections"
    name = "Connections"
    url ="/connections"
    weight = 30
 [[menu.footer]]
    page = "Work"
    name = "Work"
    identifier = "work"
    url = "/work"
    weight = 40

 [[menu.featured]]
    name= "Manifesto"
    url = "/manifesto"
    weight = -180
    pre = "/images/trex-logo.svg"
    post = "Read which vision we want to achieve, how, and why matter for us"
 [[menu.featured]]
    name = "Connections"    
    url = "/connections"
    weight = -170
    pre = "/images/connect with us.svg"
    post = "If you share the values in the Manifesto, you should check it out"
 [[menu.featured]]
    name = "Work"
    url = "/work"
    weight = -160
    pre = "/images/reports.svg"
    post = "Our last activities, from the various project under the tracking.exposed umbrella"
