baseURL = "/"
languageCode = "en-us"
title = "Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[params]
    subtitle = ""
    subsite = "default"
    openGraphSiteName = "Tracking Exposed"
    description = "Shining spotlights on the tracking, profiling of users and the influence of algorithms."
    tagline = "We fight for a web that is home for many, not property of the few!"

[permalinks]
    posts = "/news/:slug/"

[menu]
 [[menu.main]]
    name = "Sections"
    identifier = "sections"

 [[menu.main]]
    parent = "sections"
    name = "About"
    url ="/about"
    weight = 10
 [[menu.main]]
    parent = "sections"
    name = "What we do & get in touch"
    url = "/connect"
    weight = 20
 [[menu.main]]
    parent = "sections"
    name = "Manifesto"
    url = "/manifesto"
    weight = 30
 [[menu.main]]
    parent = "sections"
    name = "Monthly reports"
    url = "/monthly"
    weight = 40


 [[menu.main]]
    page = "Analyzed platforms"
    name = "Analyzed platforms"
    identifier = "analyzed"
    weight = 10
 [[menu.main]]
    page = "Facebook"
    identifier = "facebook"
    parent = "analyzed"
    name= "Facebook"
    url = "https://facebook.tracking.exposed"
    weight = -180
 [[menu.main]]
    page = "YouTube"
    parent = "analyzed"
    identifier = "youtube"
    name = "YouTube"
    url = "https://youtube.tracking.exposed"
    weight = -170
 [[menu.main]]
    page = "PornHub"
    parent = "analyzed"
    identifier = "pornhub"
    name = "PornHub"
    url = "https://pornhub.tracking.exposed"
    weight = -160
    
#  [[menu.main]]
#    page = "A national-declined research (Italian election)"
#    identifier = "eu19.tracking.exposed"
#    name = "EU Election 2019"
#    parent = "studies"
#    url = "https://eu19.tracking.exposed"
#    weight = -100
#  [[menu.main]]
#    page = "A national-declined research (Italian election)"
#    identifier = "elezioni.tracking.exposed"
#    parent = "studies"
#    name = "Italien Election"
#    url = "https://elezioni.tracking.exposed"
#    weight = -100
# [[menu.main]]
#    page = "PornHub"
#    identifier = "pornhub"
#    parent = "analyzed"
#    name = "PornHub"
#    url = "https://pornhub.tracking.exposed"
#    weight = -160

 [[menu.footer]]
    page = "about"
    identifier = "about"
    name = "About"
    url ="/about"
    weight = 0
 [[menu.footer]]
    page = "Monthly reports"
    identifier = "monthly"
    name = "Monthly reports"
    url = "/monthly"
 [[menu.footer]]
    page = "manifesto"
    identifier = "manifesto"
    name= "Manifesto"
    url = "/manifesto"
 [[menu.footer]]
    page = "What we do & get in touch"
    name = "What we do & get in touch"
    identifier = "connect"
    url = "/connect"

 [[menu.featured]]
    name= "Manifesto"
    url = "/manifesto"
    weight = -180
    pre = "/images/trex-logo.svg"
    post = "Read which vision we want to achieve, how, and why matter for us"
 [[menu.featured]]
    name = "What we do & get in touch"
    url = "/connect"
    weight = -170
    pre = "/images/connect with us.svg"
    post = "If you share the values in the Manifesto, you should check it out"
 [[menu.featured]]
    name = "Monthly reports"
    url = "/monthly"
    weight = -160
    pre = "/images/reports.svg"
    post = "Our last activities, from the various project under the tracking.exposed umbrella"
